# Generated by Django 3.0.5 on 2020-04-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200417_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Todo')),
            ],
        ),
    ]
