# Generated by Django 3.0.5 on 2020-05-17 08:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20200517_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_list',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='list',
            name='todo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Todo'),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 8, 13, 46, 517165, tzinfo=utc)),
        ),
    ]
