# Generated by Django 3.0.5 on 2020-05-17 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200517_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='listTask',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.List'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 9, 19, 27, 713405, tzinfo=utc)),
        ),
    ]
