# Generated by Django 3.0.6 on 2020-05-21 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200521_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 21, 14, 24, 41, 499594, tzinfo=utc)),
        ),
    ]
