# Generated by Django 3.0.6 on 2020-05-22 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200521_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 22, 14, 47, 58, 804077, tzinfo=utc)),
        ),
    ]
