# Generated by Django 3.0.6 on 2020-05-22 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200522_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 22, 15, 4, 56, 742625, tzinfo=utc)),
        ),
    ]
