# Generated by Django 3.0.6 on 2020-05-24 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200524_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 24, 3, 30, 1, 943449, tzinfo=utc)),
        ),
    ]
