# Generated by Django 3.0.6 on 2020-05-24 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200524_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 24, 5, 7, 29, 714667, tzinfo=utc)),
        ),
    ]
