# Generated by Django 3.0.6 on 2020-05-24 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200524_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 24, 5, 12, 25, 98237, tzinfo=utc)),
        ),
    ]
