# Generated by Django 3.0.6 on 2020-05-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200524_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
