# Generated by Django 3.0.6 on 2020-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200524_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
