# Generated by Django 3.0.5 on 2020-04-20 05:26

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('phoneNumber', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
