# Generated by Django 3.0.5 on 2020-04-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200421_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Unknown', max_length=255, unique=True, verbose_name='Tên Đăng Nhập'),
        ),
    ]
