# Generated by Django 3.0.5 on 2020-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200517_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(max_length=255, verbose_name='Họ Tên:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Tên Đăng Nhập:'),
        ),
    ]
