# Generated by Django 3.0.6 on 2020-05-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200517_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default='static\\media\\default-picture.png', upload_to='static/media/'),
        ),
    ]
