# Generated by Django 3.0.6 on 2020-05-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200524_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='default-picture.png', upload_to=''),
        ),
    ]
